name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        project:
          - CSharpExt.UnitTests
          - Noggog.Autofac
          - Noggog.CSharpExt
          - Noggog.CSharpExt.Json
          - Noggog.CSharpExt.Windows
          - Noggog.Testing
          - Noggog.WPF
        exclude:
          - os: ubuntu-latest
            project: Noggog.WPF
          - os: macos-latest
            project: Noggog.WPF
          - os: ubuntu-latest
            project: Noggog.CSharpExt.Windows
          - os: macos-latest
            project: Noggog.CSharpExt.Windows
          
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1000
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.*
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.*
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.*
    - name: Install dependencies
      run: |
        dotnet clean -c Release && dotnet nuget locals all --clear
        dotnet restore ${{ matrix.project }}/${{ matrix.project }}.csproj
    - name: Build
      run: dotnet build ${{ matrix.project }}/${{ matrix.project }}.csproj -c Release --no-restore
    - name: Test
      run: dotnet test ${{ matrix.project }}/${{ matrix.project }}.csproj -c Release --no-build
